[2024-07-19T15:37:08.665+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-19T15:37:08.680+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-19T15:37:08.691+0000] {taskinstance.py:2171} INFO - Starting attempt 11 of 11
[2024-07-19T15:37:08.711+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_spreadsheet> on 2024-07-18 15:04:45.851017+00:00
[2024-07-19T15:37:08.723+0000] {standard_task_runner.py:60} INFO - Started process 221 to run task
[2024-07-19T15:37:08.729+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_spreadsheet', 'manual__2024-07-18T15:04:45.851017+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmpvc5fjfoh']
[2024-07-19T15:37:08.734+0000] {standard_task_runner.py:88} INFO - Job 289: Subtask task_transform_to_spreadsheet
[2024-07-19T15:37:08.784+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-18T15:04:45.851017+00:00 [running]> on host 33f05a6d4bad
[2024-07-19T15:37:08.848+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_spreadsheet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T15:04:45.851017+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T15:04:45.851017+00:00'
[2024-07-19T15:37:08.902+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 72, in transform_to_spreadsheet
    data_frame.to_excel('dags/google_analytics_data_etl/datas/data_flat_group_by_geo_city.xlsx')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2024-07-19T15:37:08.946+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=google_analytics_data_etl, task_id=task_transform_to_spreadsheet, execution_date=20240718T150445, start_date=20240719T153708, end_date=20240719T153708
[2024-07-19T15:37:08.959+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-07-19T15:37:08.960+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-07-19T15:37:10.733+0000] {email.py:281} INFO - Sent an alert email to ['fujonfujon@gmail.com']
[2024-07-19T15:37:12.252+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 289 for task task_transform_to_spreadsheet (No module named 'openpyxl'; 221)
[2024-07-19T15:37:12.303+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-19T15:37:12.375+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
