[2024-07-19T14:04:15.901+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-19T14:04:15.937+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-19T14:04:15.941+0000] {taskinstance.py:2171} INFO - Starting attempt 6 of 6
[2024-07-19T14:04:15.997+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_spreadsheet> on 2024-07-18 15:04:45.851017+00:00
[2024-07-19T14:04:16.031+0000] {standard_task_runner.py:60} INFO - Started process 81 to run task
[2024-07-19T14:04:16.037+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_spreadsheet', 'manual__2024-07-18T15:04:45.851017+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmp5lu1psnx']
[2024-07-19T14:04:16.044+0000] {standard_task_runner.py:88} INFO - Job 256: Subtask task_transform_to_spreadsheet
[2024-07-19T14:04:16.169+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-18T15:04:45.851017+00:00 [running]> on host 0786c3d39089
[2024-07-19T14:04:16.466+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_spreadsheet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T15:04:45.851017+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T15:04:45.851017+00:00'
[2024-07-19T14:04:16.570+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 72, in transform_to_spreadsheet
    data_frame.to_excel('dags/google_analytics_data_etl/datas/data_flat_group_by_geo_city.xlsx')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2024-07-19T14:04:16.597+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=google_analytics_data_etl, task_id=task_transform_to_spreadsheet, execution_date=20240718T150445, start_date=20240719T140415, end_date=20240719T140416
[2024-07-19T14:04:16.613+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-07-19T14:04:16.614+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-07-19T14:04:16.615+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-07-19T14:04:16.616+0000] {taskinstance.py:1116} ERROR - Error when executing task_fail_email_alert callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2335, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2500, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2517, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 72, in transform_to_spreadsheet
    data_frame.to_excel('dags/google_analytics_data_etl/datas/data_flat_group_by_geo_city.xlsx')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1113, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/google_analytics_data_etl/google_analytics_data_etl.py", line 34, in task_fail_email_alert
    return send_mail.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-07-19T14:04:16.648+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 256 for task task_transform_to_spreadsheet (No module named 'openpyxl'; 81)
[2024-07-19T14:04:16.682+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-19T14:04:16.701+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
