[2024-07-18T15:04:48.281+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_load_data_postgres manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-18T15:04:48.297+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_load_data_postgres manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-18T15:04:48.299+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-07-18T15:04:48.345+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): task_load_data_postgres> on 2024-07-18 15:04:45.851017+00:00
[2024-07-18T15:04:48.355+0000] {standard_task_runner.py:60} INFO - Started process 854 to run task
[2024-07-18T15:04:48.363+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_load_data_postgres', 'manual__2024-07-18T15:04:45.851017+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmpb4k6gvje']
[2024-07-18T15:04:48.365+0000] {standard_task_runner.py:88} INFO - Job 149: Subtask task_load_data_postgres
[2024-07-18T15:04:48.463+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_load_data_postgres manual__2024-07-18T15:04:45.851017+00:00 [running]> on host 3d44d7374020
[2024-07-18T15:04:48.586+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_load_data_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T15:04:45.851017+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T15:04:45.851017+00:00'
[2024-07-18T15:04:48.599+0000] {sql.py:276} INFO - Executing: INSERT INTO your_table (col1, col2) VALUES (%s, %s)
[2024-07-18T15:04:48.627+0000] {base.py:83} INFO - Using connection ID 'postgres_google_analytics' for task execution.
[2024-07-18T15:04:48.646+0000] {base.py:83} INFO - Using connection ID 'postgres_google_analytics' for task execution.
[2024-07-18T15:04:48.649+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-07-18T15:04:48.669+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_analytics_data_etl, task_id=task_load_data_postgres, execution_date=20240718T150445, start_date=20240718T150448, end_date=20240718T150448
[2024-07-18T15:04:48.684+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 149 for task task_load_data_postgres (connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 854)
[2024-07-18T15:04:48.733+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-18T15:04:48.778+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
