[2024-07-17T14:51:57.440+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat manual__2024-07-17T14:09:16.168610+00:00 [queued]>
[2024-07-17T14:51:57.467+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat manual__2024-07-17T14:09:16.168610+00:00 [queued]>
[2024-07-17T14:51:57.467+0000] {taskinstance.py:2171} INFO - Starting attempt 5 of 6
[2024-07-17T14:51:57.508+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_flat> on 2024-07-17 14:09:16.168610+00:00
[2024-07-17T14:51:57.531+0000] {standard_task_runner.py:60} INFO - Started process 1888 to run task
[2024-07-17T14:51:57.561+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_flat', 'manual__2024-07-17T14:09:16.168610+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmppyzq63le']
[2024-07-17T14:51:57.568+0000] {standard_task_runner.py:88} INFO - Job 70: Subtask task_transform_to_flat
[2024-07-17T14:51:57.734+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_flat manual__2024-07-17T14:09:16.168610+00:00 [running]> on host f5f2893b4d65
[2024-07-17T14:51:57.881+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_flat' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T14:09:16.168610+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T14:09:16.168610+00:00'
[2024-07-17T14:51:57.975+0000] {logging_mixin.py:188} INFO - {'event_date': '20230101', 'event_value_in_usd': None, 'event_bundle_sequence_id': '10', 'event_server_timestamp_offset': '346381', 'user_id': None, 'user_pseudo_id': '7617C4B61F7E490BAE32F46345741A13', 'privacy_info_analytics_storage': 'Yes', 'privacy_info_ads_storage': 'Yes', 'privacy_info_uses_transient_token': 'No', 'user_first_touch_timestamp': '1669870350840000', 'user_ltv': None, 'device_category': 'tablet', 'device_mobile_brand_name': 'Apple', 'device_mobile_model_name': 'iPad (9th gen)', 'device_mobile_marketing_name': None, 'device_mobile_os_hardware_model': 'iPad12,1', 'device_operating_system': 'iOS', 'device_operating_system_version': 'iOS 15.6.1', 'device_vendor_id': '23E70A11-E173-4B39-8746-0C59BC996517', 'device_advertising_id': '', 'device_language': 'en-au', 'device_is_limited_ad_tracking': 'Yes', 'device_time_zone_offset_seconds': '36000', 'device_browser': None, 'device_browser_version': None, 'device_web_info': None, 'geo_continent': 'Oceania', 'geo_country': 'Australia', 'geo_region': 'Queensland', 'geo_city': 'Gold Coast', 'geo_sub_continent': 'Australasia', 'geo_metro': '(not set)', 'stream_id': '1653913388', 'platform': 'IOS', 'event_dimensions': None, 'ecommerce': None}
[2024-07-17T14:51:57.988+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 48, in transform_to_flat
    data_frame = pd.read_json(flat_data)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 716, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 456, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>
[2024-07-17T14:51:58.006+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_analytics_data_etl, task_id=task_transform_to_flat, execution_date=20240717T140916, start_date=20240717T145157, end_date=20240717T145158
[2024-07-17T14:51:58.034+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 70 for task task_transform_to_flat (Invalid file path or buffer object type: <class 'list'>; 1888)
[2024-07-17T14:51:58.054+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T14:51:58.077+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
