[2024-07-18T14:01:49.775+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T14:01:49.795+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T14:01:49.799+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 4
[2024-07-18T14:01:49.834+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_spreadsheet> on 2024-07-17 15:00:53.249913+00:00
[2024-07-18T14:01:49.842+0000] {standard_task_runner.py:60} INFO - Started process 217 to run task
[2024-07-18T14:01:49.849+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_spreadsheet', 'manual__2024-07-17T15:00:53.249913+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmpif905qdo']
[2024-07-18T14:01:49.851+0000] {standard_task_runner.py:88} INFO - Job 124: Subtask task_transform_to_spreadsheet
[2024-07-18T14:01:49.906+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-17T15:00:53.249913+00:00 [running]> on host 3d44d7374020
[2024-07-18T14:01:49.989+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_spreadsheet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T15:00:53.249913+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T15:00:53.249913+00:00'
[2024-07-18T14:01:50.003+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 66, in transform_to_spreadsheet
    data_frame = pd.DataFrame(data_flat)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 817, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
[2024-07-18T14:01:50.024+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_analytics_data_etl, task_id=task_transform_to_spreadsheet, execution_date=20240717T150053, start_date=20240718T140149, end_date=20240718T140150
[2024-07-18T14:01:50.057+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 124 for task task_transform_to_spreadsheet (DataFrame constructor not properly called!; 217)
[2024-07-18T14:01:50.098+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-18T14:01:50.118+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
