[2024-07-18T14:18:26.502+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T14:18:26.514+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T14:18:26.517+0000] {taskinstance.py:2171} INFO - Starting attempt 11 of 12
[2024-07-18T14:18:26.532+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_spreadsheet> on 2024-07-17 15:00:53.249913+00:00
[2024-07-18T14:18:26.541+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-18T14:18:26.544+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_spreadsheet', 'manual__2024-07-17T15:00:53.249913+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmp_l43a817']
[2024-07-18T14:18:26.545+0000] {standard_task_runner.py:88} INFO - Job 141: Subtask task_transform_to_spreadsheet
[2024-07-18T14:18:26.599+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet manual__2024-07-17T15:00:53.249913+00:00 [running]> on host 3d44d7374020
[2024-07-18T14:18:26.696+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_spreadsheet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T15:00:53.249913+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T15:00:53.249913+00:00'
[2024-07-18T14:18:26.723+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 69, in transform_to_spreadsheet
    data_frame.to_excel('dags/google_analytics_data_etl/datas/data_flat_group_by_geo_city.xlsx')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2024-07-18T14:18:26.747+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_analytics_data_etl, task_id=task_transform_to_spreadsheet, execution_date=20240717T150053, start_date=20240718T141826, end_date=20240718T141826
[2024-07-18T14:18:26.766+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 141 for task task_transform_to_spreadsheet (No module named 'openpyxl'; 97)
[2024-07-18T14:18:26.801+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-18T14:18:26.818+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
