[2024-07-17T14:14:21.307+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat manual__2024-07-17T14:05:48.098724+00:00 [queued]>
[2024-07-17T14:14:21.314+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat manual__2024-07-17T14:05:48.098724+00:00 [queued]>
[2024-07-17T14:14:21.315+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-07-17T14:14:21.332+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_flat> on 2024-07-17 14:05:48.098724+00:00
[2024-07-17T14:14:21.339+0000] {standard_task_runner.py:60} INFO - Started process 1273 to run task
[2024-07-17T14:14:21.341+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_flat', 'manual__2024-07-17T14:05:48.098724+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmpmli2j0c7']
[2024-07-17T14:14:21.346+0000] {standard_task_runner.py:88} INFO - Job 49: Subtask task_transform_to_flat
[2024-07-17T14:14:21.415+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_flat manual__2024-07-17T14:05:48.098724+00:00 [running]> on host f5f2893b4d65
[2024-07-17T14:14:21.501+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_flat' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T14:05:48.098724+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T14:05:48.098724+00:00'
[2024-07-17T14:14:21.628+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 6, in transform_to_flat
    data_frame = pd.read_json(raw_data_json)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 716, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 456, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>
[2024-07-17T14:14:21.674+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_analytics_data_etl, task_id=task_transform_to_flat, execution_date=20240717T140548, start_date=20240717T141421, end_date=20240717T141421
[2024-07-17T14:14:21.695+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 49 for task task_transform_to_flat (Invalid file path or buffer object type: <class 'list'>; 1273)
[2024-07-17T14:14:21.763+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T14:14:21.824+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
