[2024-07-18T13:56:43.357+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T13:56:43.368+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T13:56:43.369+0000] {taskinstance.py:2171} INFO - Starting attempt 4 of 5
[2024-07-18T13:56:43.388+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_flat> on 2024-07-17 15:00:53.249913+00:00
[2024-07-18T13:56:43.393+0000] {standard_task_runner.py:60} INFO - Started process 122 to run task
[2024-07-18T13:56:43.399+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_flat', 'manual__2024-07-17T15:00:53.249913+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmpzn6pcvm6']
[2024-07-18T13:56:43.401+0000] {standard_task_runner.py:88} INFO - Job 116: Subtask task_transform_to_flat
[2024-07-18T13:56:43.551+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_flat manual__2024-07-17T15:00:53.249913+00:00 [running]> on host 3d44d7374020
[2024-07-18T13:56:43.656+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_flat' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T15:00:53.249913+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T15:00:53.249913+00:00'
[2024-07-18T13:56:43.789+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 51, in transform_to_flat
    ti.xcom.push(key='transform_flat_group_geo_city', value=data_to_dict)
AttributeError: 'TaskInstance' object has no attribute 'xcom'
[2024-07-18T13:56:43.817+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_analytics_data_etl, task_id=task_transform_to_flat, execution_date=20240717T150053, start_date=20240718T135643, end_date=20240718T135643
[2024-07-18T13:56:43.841+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 116 for task task_transform_to_flat ('TaskInstance' object has no attribute 'xcom'; 122)
[2024-07-18T13:56:43.896+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-18T13:56:43.927+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
