[2024-07-18T13:55:40.898+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat_by_operation manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T13:55:40.914+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat_by_operation manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T13:55:40.915+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-07-18T13:55:40.938+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_flat_by_operation> on 2024-07-17 15:00:53.249913+00:00
[2024-07-18T13:55:40.945+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2024-07-18T13:55:40.950+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_flat_by_operation', 'manual__2024-07-17T15:00:53.249913+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmpo4idstpx']
[2024-07-18T13:55:40.952+0000] {standard_task_runner.py:88} INFO - Job 114: Subtask task_transform_to_flat_by_operation
[2024-07-18T13:55:41.004+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_flat_by_operation manual__2024-07-17T15:00:53.249913+00:00 [running]> on host 3d44d7374020
[2024-07-18T13:55:41.110+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_flat_by_operation' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T15:00:53.249913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T15:00:53.249913+00:00'
[2024-07-18T13:55:41.279+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 59, in transform_to_flat_by_operation
    data_to_dict = data.to_dict(data)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 1988, in to_dict
    return to_dict(self, orient, into, index)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/methods/to_dict.py", line 83, in to_dict
    orient = orient.lower()  # type: ignore[assignment]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'lower'
[2024-07-18T13:55:41.306+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_analytics_data_etl, task_id=task_transform_to_flat_by_operation, execution_date=20240717T150053, start_date=20240718T135540, end_date=20240718T135541
[2024-07-18T13:55:41.327+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 114 for task task_transform_to_flat_by_operation ('DataFrame' object has no attribute 'lower'; 102)
[2024-07-18T13:55:41.362+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-18T13:55:41.397+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
