[2024-07-18T13:56:51.202+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat_by_operation manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T13:56:51.214+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat_by_operation manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T13:56:51.215+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2024-07-18T13:56:51.230+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_flat_by_operation> on 2024-07-17 15:00:53.249913+00:00
[2024-07-18T13:56:51.237+0000] {standard_task_runner.py:60} INFO - Started process 130 to run task
[2024-07-18T13:56:51.244+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_flat_by_operation', 'manual__2024-07-17T15:00:53.249913+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmprzk1r835']
[2024-07-18T13:56:51.245+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask task_transform_to_flat_by_operation
[2024-07-18T13:56:51.297+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_flat_by_operation manual__2024-07-17T15:00:53.249913+00:00 [running]> on host 3d44d7374020
[2024-07-18T13:56:51.384+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_flat_by_operation' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T15:00:53.249913+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T15:00:53.249913+00:00'
[2024-07-18T13:56:51.508+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 60, in transform_to_flat_by_operation
    ti.xcom(key='transform_flat_group_event_name', value=data_to_dict)
AttributeError: 'TaskInstance' object has no attribute 'xcom'
[2024-07-18T13:56:51.528+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_analytics_data_etl, task_id=task_transform_to_flat_by_operation, execution_date=20240717T150053, start_date=20240718T135651, end_date=20240718T135651
[2024-07-18T13:56:51.544+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 119 for task task_transform_to_flat_by_operation ('TaskInstance' object has no attribute 'xcom'; 130)
[2024-07-18T13:56:51.574+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-18T13:56:51.601+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
