[2024-07-19T15:37:08.736+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet_2 manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-19T15:37:08.749+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet_2 manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-19T15:37:08.752+0000] {taskinstance.py:2171} INFO - Starting attempt 11 of 11
[2024-07-19T15:37:08.766+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_spreadsheet_2> on 2024-07-18 15:04:45.851017+00:00
[2024-07-19T15:37:08.776+0000] {standard_task_runner.py:60} INFO - Started process 222 to run task
[2024-07-19T15:37:08.781+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_spreadsheet_2', 'manual__2024-07-18T15:04:45.851017+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmp_9agl5y7']
[2024-07-19T15:37:08.783+0000] {standard_task_runner.py:88} INFO - Job 290: Subtask task_transform_to_spreadsheet_2
[2024-07-19T15:37:08.856+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet_2 manual__2024-07-18T15:04:45.851017+00:00 [running]> on host 33f05a6d4bad
[2024-07-19T15:37:08.975+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_spreadsheet_2' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T15:04:45.851017+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T15:04:45.851017+00:00'
[2024-07-19T15:37:08.993+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 78, in transform_to_spreadsheet_2
    data_frame.to_excel('dags/google_analytics_data_etl/datas/data_flat_group_by_event_name.xlsx')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2024-07-19T15:37:09.058+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=google_analytics_data_etl, task_id=task_transform_to_spreadsheet_2, execution_date=20240718T150445, start_date=20240719T153708, end_date=20240719T153709
[2024-07-19T15:37:09.074+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-07-19T15:37:09.078+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-07-19T15:37:11.855+0000] {email.py:281} INFO - Sent an alert email to ['fujonfujon@gmail.com']
[2024-07-19T15:37:13.512+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 290 for task task_transform_to_spreadsheet_2 (No module named 'openpyxl'; 222)
[2024-07-19T15:37:13.561+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-19T15:37:13.587+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
