[2024-07-19T14:42:47.403+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet_2 manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-19T14:42:47.411+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet_2 manual__2024-07-18T15:04:45.851017+00:00 [queued]>
[2024-07-19T14:42:47.413+0000] {taskinstance.py:2171} INFO - Starting attempt 7 of 7
[2024-07-19T14:42:47.427+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_spreadsheet_2> on 2024-07-18 15:04:45.851017+00:00
[2024-07-19T14:42:47.433+0000] {standard_task_runner.py:60} INFO - Started process 74 to run task
[2024-07-19T14:42:47.437+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_spreadsheet_2', 'manual__2024-07-18T15:04:45.851017+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmpp173efj1']
[2024-07-19T14:42:47.438+0000] {standard_task_runner.py:88} INFO - Job 263: Subtask task_transform_to_spreadsheet_2
[2024-07-19T14:42:47.505+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_spreadsheet_2 manual__2024-07-18T15:04:45.851017+00:00 [running]> on host 7eef33db0bc5
[2024-07-19T14:42:47.582+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_spreadsheet_2' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T15:04:45.851017+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T15:04:45.851017+00:00'
[2024-07-19T14:42:47.618+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 78, in transform_to_spreadsheet_2
    data_frame.to_excel('dags/google_analytics_data_etl/datas/data_flat_group_by_event_name.xlsx')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2024-07-19T14:42:47.650+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=google_analytics_data_etl, task_id=task_transform_to_spreadsheet_2, execution_date=20240718T150445, start_date=20240719T144247, end_date=20240719T144247
[2024-07-19T14:42:47.658+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-07-19T14:42:47.659+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-07-19T14:42:49.771+0000] {email.py:281} INFO - Sent an alert email to ['heft0305@gmail.com']
[2024-07-19T14:42:51.328+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 263 for task task_transform_to_spreadsheet_2 (No module named 'openpyxl'; 74)
[2024-07-19T14:42:51.376+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-19T14:42:51.485+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
